In [1]:
import os
import sys

sys.path.append('D:\\Dropbox\\89_其他應用\\GitHub\\PETs-Experiment')
os.chdir('D:\\Dropbox\\89_其他應用\\GitHub\\PETs-Experiment\\demo')
import PETs_Experiment

In [2]:
loader = PETs_Experiment.Loader(filepath = '../[sunset]/data/[Adt Income] adult.csv'
                               ,na_values = {k : '?' for k in ['workclass'
                                                              ,'occupation'
                                                              ,'native-country'
                                                              ]
                                            }
                               )
print(loader.data.head(1))

In [ ]:
preproc = PETs_Experiment.Preprocessor(
     data = loader.data
    ,missing=True
        ,missing_method  = 'drop'
        ,missing_columns = None
    ,outlier=True
        ,outlier_method  = 'IQR'
        ,outlier_columns = {'ignore': ['hours-per-week']}
    ,encoding=True
        ,encoding_method  = 'Label'
        ,encoding_columns = None
    ,scaling=False
)
print('\n\n\n')
print(preproc.data.head(1))
print('\n\n\n')
print(preproc.encoder)


        # ,scaling_method  = 'Standard'
        # ,scaling_columns = None
# print('\n\n\n')
# print(Preprocessor.scaler)


Preprocessor - Missingist (Drop): Dropped 3620 rows.
Preprocessor - Outlierist (IQR): Dropped  1331 rows on fnlwgt         . Kept [-63418.375, 418732.625] only.
Preprocessor - Outlierist (IQR): Dropped  2140 rows on capital-loss   . Kept [0.0, 0.0] only.
Preprocessor - Outlierist (IQR): Dropped  3790 rows on capital-gain   . Kept [0.0, 0.0] only.
Preprocessor - Outlierist (IQR): Dropped   294 rows on educational-num. Kept [3.0, 19.0] only.
Preprocessor - Outlierist (IQR): Dropped   269 rows on age            . Kept [-0.5, 75.5] only.
Preprocessor - Outlierist (IQR): Totally Dropped  7569 in 45222 rows.
Preprocessor - Encoder (Label): Column gender          been labelized from 0 to  1.
Preprocessor - Encoder (Label): Column occupation      been labelized from 0 to 13.
Preprocessor - Encoder (Label): Column education       been labelized from 0 to 13.
Preprocessor - Encoder (Label): Column marital-status  been labelized from 0 to  6.
Preprocessor - Encoder (Label): Column income         

In [ ]:
synthesizer = PETs_Experiment.Synthesizer(data = preproc.data
                                         ,synthesizing_method = 'sdv-singletable-gaussiancoupula'
                                         )
synthesizer.fit_sample()
print(synthesizer.data_syn.head(1))

Synthesizer (SDV - SingleTable): Metafile loading time: 0.0469 sec.
Synthesizer (SDV - SingleTable): Fitting  GaussianCoupula.
Synthesizer (SDV - SingleTable): Fitting  GaussianCoupula spent 19.2755 sec.
Synthesizer (SDV - SingleTable): Sampling GaussianCoupula # 37653 rows (same as raw) in 2.1546 sec.
   age  workclass  fnlwgt  education  educational-num  marital-status  \
0   55          1   52595         11                8               2   

   occupation  relationship  race  gender  capital-gain  capital-loss  \
0           8             0     4       1             0             0   

   hours-per-week  native-country  income  
0              54              32       0  


In [ ]:
postproc = PETs_Experiment.Postprocessor(data = synthesizer.data_syn
                                        ,encoder = getattr(Preprocessor ,'encoder' ,None)
                                        ,scaler  = getattr(Preprocessor ,'scaler'  ,None)
                                        )
print(postproc.data.head(1))

NameError: name 'Preprocessor' is not defined

In [ ]:
import os
os.chdir('D:\\Dropbox\\89_其他應用\\GitHub\\PETs-Experiment')

import PETs_Experiment

para_Executor = {
     'Loader_filepath'  : '[sunset]/data/[Adt Income] adult.csv'
    ,'Loader_na_values' : {k : '?' for k in ['workclass' ,'occupation' ,'native-country']}
    ,'Preprocessor_missing_method'  : 'drop'
    ,'Preprocessor_outlier_method'  : 'IQR'
    ,'Preprocessor_outlier_columns' : {'ignore': ['hours-per-week']}
    ,'Preprocessor_encoding_method' : 'Label'
    ,'Preprocessor_scaling'         : True
    ,'Preprocessor_scaling_method'  : 'Standard'
    ,'Preprocessor_scaling_columns' : {'focus' : 'fnlwgt'}
    ,'Synthesizer_synthesizing_method' : 'sdv-singletable-gaussiancoupula'
}

executor = PETs_Experiment.Executor(**para_Executor)
executor.run()

Preprocessor - Missingist (Drop): Dropped 3620 rows.
Preprocessor - Outlierist (IQR): Dropped   269 rows on age            . Kept [-0.5, 75.5] only.
Preprocessor - Outlierist (IQR): Dropped  2140 rows on capital-loss   . Kept [0.0, 0.0] only.
Preprocessor - Outlierist (IQR): Dropped  1331 rows on fnlwgt         . Kept [-63418.375, 418732.625] only.
Preprocessor - Outlierist (IQR): Dropped  3790 rows on capital-gain   . Kept [0.0, 0.0] only.
Preprocessor - Outlierist (IQR): Dropped   294 rows on educational-num. Kept [3.0, 19.0] only.
Preprocessor - Outlierist (IQR): Totally Dropped  7569 in 45222 rows.
Preprocessor - Encoder (Label): Column race            been labelized from 0 to  4.
Preprocessor - Encoder (Label): Column marital-status  been labelized from 0 to  6.
Preprocessor - Encoder (Label): Column occupation      been labelized from 0 to 13.
Preprocessor - Encoder (Label): Column relationship    been labelized from 0 to  5.
Preprocessor - Encoder (Label): Column workclass      

In [ ]:
 executor.synthesizer

In [ ]:
import numpy as np
test = np.zeros(shape=(len(executor.synthesizer.data_syn['fnlwgt']), 12) )
print(test)
test[:,0] = executor.synthesizer.data_syn['fnlwgt'][:,0] # .values


# executor.preprocessor.scaler['fnlwgt'].inverse_transform(

#     test
# )

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


KeyError: 'key of type tuple not found and not a MultiIndex'

In [ ]:
executor.synthesizer.data_syn['fnlwgt']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
37648    0.0
37649    0.0
37650    0.0
37651    0.0
37652    0.0
Name: fnlwgt, Length: 37653, dtype: float64